### ISSUE TITLE
Firebase.FCM does not work with PostgreSQL

### ISSUE THREAD

**Issue by wojtek2288** [leancodepl/corelibrary#382]
Using postgres, FCMClient, SendToUsersAsync throws an exception when passing `HashSet<Guid>` and expecting `IReadOnlySet<Guid>`

```
[12:31:21 ERR] R-FAULT loopback://localhost/***-api-events be987b02-09f5-4ae5-be93-382c7357a9c1 ***.Core.Domain.Events.Events.EventLocationOrTimingChanged ***.Core.Services.Processes.Firebase.NotifyOnEventLocationOrTimingChanged(00:00:00.0153645)
***-integration_tests-1  | System.NotSupportedException: IEnumerable parameters are not supported, pass an array or List instead
***-integration_tests-1  |    at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByClrType(Type type)
***-integration_tests-1  |    at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
***-integration_tests-1  |    at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
***-integration_tests-1  |    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
***-integration_tests-1  |    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
***-integration_tests-1  |    at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
***-integration_tests-1  |    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
***-integration_tests-1  |    at LeanCode.Dapper.DbContextDapperExtensions.WithConnectionAsync[TResult](DbContext context, Func`2 call)
***-integration_tests-1  |    at LeanCode.Firebase.FCM.EntityFramework.PushNotificationTokenStore`1.GetTokensAsync(IReadOnlySet`1 userIds, CancellationToken cancellationToken)
***-integration_tests-1  |    at LeanCode.Firebase.FCM.FCMClient.SendToUsersAsync(IReadOnlySet`1 userIds, MulticastMessage message, Boolean dryRun, CancellationToken cancellationToken)
***-integration_tests-1  |    at ***.Core.Services.Processes.Firebase.NotifyOnEventLocationOrTimingChanged.Consume(ConsumeContext`1 context) in /app/code/src/Core/***.Core.Services/Processes/Firebase/NotifyOnEventLocationOrTimingChanged.cs:line 49
```

**Comment by mateuszkulak** [comment]
Issue solved in PR https://github.com/leancodepl/corelibrary/pull/393/.
